{
  "id": 10405,
  "origin_website": "Jove",
  "title": "Application of 3D Printing in the Construction of Burr Hole Ring for Deep Brain Stimulation Implants",
  "procedures": [
    "1. Drawing a two dimensional (2D)-image of a burr hole ring\nOpen the 2D computer aided design (CAD) software and then create a graphical document.\nClick Draw | Line and draw a reference point with a solid line on the drawing. Click Modify | Offset, and type the specific offset distance in the command line.\nClick on the object and press by the left mouse button to create a solid line. Click Modify | Trim, select the area to be trimmed and click on the extra line.\nTake the inner burr hole ring for example, draw three different views of the inner ring based on the predetermined size in the CAD software. First, draw the front view and modify the graph carefully until it matches the structure expected (Figure 1d).\nDraw the top view by clicking Draw | Line to construct the reference point first and then click on Draw | Circle | Center, Diameter, and input the quantitative value of specific radius of circle or diameter in the command window. Click on the center of the reference point to form a circle (Figure 1f).\nDraw the left view of the inner burr hole ring with the same approach as that of the front view (Figure 1e).\nClick on Dimension | Diameter, and then click on the circumference to mark the diameter of the circle (Figure 1f).\nClick on Dimension | Linear and mark the length and thickness of all associated structures (Figure 1d,e). Click Dimension | Radius to mark the angle of the chamber (Figure 1d).\nUsing the same protocol, construct two-dimensional drawings of the outer burr hole ring, and mark the actual size and the labeling (Figure 1a - c).",
    "Add technical requirements of the production process, including strength, toughness and lack of cracks. Moreover, smoothing of the outer wall is needed.\nClink on Save to save the 2D-image of the burr hole ring.\n\tNOTE: All of these structures mentioned above are in the units of millimeters (mm).\n2. Construction of a 3D-image of the burr hole ring\nStart the 3D drawing software (see the Table of Materials). Select New | Part | Solid and uncheck using the default template. Select part_solid in new file options and click on Ok to create a new interface for setting up a physical part model.\nClick on Part feature in the menu manager on the right and select Create | Solid | Add sheet. In the SOLID drop-down menu, select Rotate | Done. Click on the trace of the preliminary sketch. Select the \"front\" plane as the sketch plane, then click default under SKET VIEW.\nSelect the dotted line on the right toolbar of the window and draw the top section of the part in the two-dimensional sketch. The specific size shall be subject to the two-dimensional drawing. Then click Conform, and select Done in the Protrusion window of protrusion. Click on the Datum plane icon.\nIn menu manager, select Create | Solid | Add sheet, and Rotate | Done. Click Bilateral in the properties menu and click Done.\nClick on Front | Forward | Default and then Datum plane | Dotted Line to construct the cross section of the hook of the outer burr hole ring. Then click Conform followed by Done in menu manager. Input \"50\" in Angle in indicated direction[45.0000], and then click Done in the Protrusion window and finally, click on the Coloring button.\n\tNOTE: The unit of the angle is degree (°).",
    "Select Redefine in the part feature and click the line structure of the hook. Input the command Section | Define | Sketch.\nClick the Dotted line icon, create two square embossments on the hook section, then input command OK | Done | Coloring.\nClick the Datum axis icon, then input the command Insert a datum | Cross, click the center axis of the line structure, click Angle in datum plane, and then click the \"front\" plane in the line structure view. Click input value in the offset menu. Input \"-45\" in \"Angle in indicated direction[45.0000].\n\tNOTE: The unit of the angle is degree (°).\nClick on Features | Copy | Mirror. Click on the hook as the object and input command Done select | Done. Click the datum plane to complete the copy. Similarly, the remaining two hooks are copied in this way. Click on Create concentric circle to construct a circle with a radius of 7.23 mm, click the Segmentation of primitives at selected points icon to remove the unnecessary lines of the circle.\nClick the Solid line button in the right toolbar to create a complete outer wall section. Then input the command OK | Done.\n\tNOTE: The unit of the radius is millimeter (mm).\nInput \"4\" in Enter depth, then click on Coloring. Input the command Mirror | Done. Then click on the object and click Done. Click the datum plane to complete the copy.\nInput the command Copy | Mirror | Done, and select two outer walls in different directions, click Done to conform. Click the datum plane to complete the copy.",
    "Input the command View | Model Settings | Color and appearance | Add. Adjust the RGB color slider and adjust the color to brown to show the graphic details more visually. Then input the command Close | Settings | OK.\nClick the button Eliminating hidden lines, click the Create concentric circle, continue to create an outer edge on the outer wall, click the Segmentation of primitives at selected points button to remove excess lines, and click the Solid line button to connect the newly added outer edge into a complete section. Click Ok.\nInput \"0.8\" in Inter depth. Click Ok in the Protrusion window. In menu manager, input the command Copy | Mirror | Done. Click the object and click done. Input the command Generate benchmark | Offset.\n\tNOTE: The unit of the depth is millimeter (mm).\nClick the Input value in the Offset and enter \"0.4\" as the Isometric of the specified direction, then click Done.\n\tNOTE: The unit of the offset is millimeter (mm).\nInput the command Copy | Mirror | Done, click the outer wall. Input the command Done select | Done. Click Done select and click Done. Click the datum of the image to complete the copy. In this way, the mirror operation of the outer wall and the square embossing is completed respectively.\nInput the command File | Copy, select save format as STL (*stl) in the part type drop-down menu, enter part number and click Ok.\nIn the Output STL dialog box, adjust the chord height to 0.006 and the angle control to 0.00001. Input the command Apply | OK.\nUse the same methods as above to build the 3D image of the inner ring.\n3. Using 3D printer to print the physical model of burr hole ring",
    "Open the model detecting software, input the command Project | Open, choose one STL file in the Open file pop-up dialog box, then click Open. In this software, a warning will appear if defects are detected in this model (Figure 3). If found, repair the model before printing. If there are no defects, click Output.\nAfter confirming that the outer ring is complete, input the command Part | Export part | as STL | Save. Use the above instructions to detect the defects of the inner ring.\nFollowing model detection, the printed path needs to be designed. Open the slicing software, click File | Load model file, click on one STL file and click Open to import.\nClick the left mouse button to choose the moving track of the part, adjust the position of parts. On the left side of the screen, set the print speed to 30 mm/s, printing temperature to 210 °C and bed temperature to 80 °C (Figure 4).\nClick Toolpath to SD to save the file in Gcode format to generate printed path (Figure 3).\nStart the 3D printers, click the Preheating button on the main interface, set the preheat temperature of the bed to 80 °C and the nozzle temperature to 210 °C. Click Print when the temperature rises to the preset value, select the target file and click Confirm to start printing.\nThe outer ring will be printed first (Figure 5a). After the bottom supporting grid has been constructed, the printing nozzle begins to construct the outer ring vertically layer by layer (Figure 5b - d). This process takes about 13 min.\nAfter the outer ring is formed, the printer nozzle continues to make the inner ring on the right side (Figure 5c,d), which takes about 8 min.",
    "Remove both parts from the platform after cooling and being formed (Figure 5e,f).\n4. Measurement of absolute error\nTo measure the absolute error, select five printed parts randomly. Measure and record the parameters of each part with Vernier calipers. Choose the measurement accuracy at 0.02 mm.\nCalculate the mean error of each part and the error range of the absolute error (Figure 6a,b).\nSubscription Required. Please recommend JoVE to your librarian."
  ],
  "subjectAreas": [
    "Behavior"
  ],
  "bigAreas": [
    "Ecology & Environmental Biology"
  ]
}